# Generated by Django 5.0.7 on 2024-07-28 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('skill1', models.CharField(blank=True, max_length=50, null=True)),
                ('skill2', models.CharField(blank=True, max_length=50, null=True)),
                ('skill3', models.CharField(blank=True, max_length=50, null=True)),
                ('skill4', models.CharField(blank=True, max_length=50, null=True)),
                ('skill5', models.CharField(blank=True, max_length=50, null=True)),
                ('degree1', models.CharField(blank=True, max_length=100, null=True)),
                ('college1', models.CharField(blank=True, max_length=100, null=True)),
                ('year1', models.PositiveIntegerField(blank=True, null=True)),
                ('degree2', models.CharField(blank=True, max_length=100, null=True)),
                ('college2', models.CharField(blank=True, max_length=100, null=True)),
                ('year2', models.PositiveIntegerField(blank=True, null=True)),
                ('degree3', models.CharField(blank=True, max_length=100, null=True)),
                ('college3', models.CharField(blank=True, max_length=100, null=True)),
                ('year3', models.PositiveIntegerField(blank=True, null=True)),
                ('lang1', models.CharField(blank=True, max_length=50, null=True)),
                ('lang2', models.CharField(blank=True, max_length=50, null=True)),
                ('lang3', models.CharField(blank=True, max_length=50, null=True)),
                ('project1', models.CharField(blank=True, max_length=100, null=True)),
                ('desc1', models.TextField(blank=True, null=True)),
                ('project2', models.CharField(blank=True, max_length=100, null=True)),
                ('desc2', models.TextField(blank=True, null=True)),
                ('company1', models.CharField(blank=True, max_length=100, null=True)),
                ('post1', models.CharField(blank=True, max_length=100, null=True)),
                ('duration1', models.CharField(blank=True, max_length=50, null=True)),
                ('lin11', models.URLField(blank=True, null=True)),
                ('company2', models.CharField(blank=True, max_length=100, null=True)),
                ('post2', models.CharField(blank=True, max_length=100, null=True)),
                ('duration2', models.CharField(blank=True, max_length=50, null=True)),
                ('lin21', models.URLField(blank=True, null=True)),
                ('ach1', models.CharField(blank=True, max_length=200, null=True)),
                ('ach2', models.CharField(blank=True, max_length=200, null=True)),
                ('ach3', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
